#http://superuser.com/questions/540391/x-error-of-failed-request-badcursor-invalid-cursor-parameter-when-recording-x  


language: ruby 
cache: apt

env:
  global:
    secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="



matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - develop
    
before_install:
  - source ./config_travis.cfg
  - set_env
  - before_install

  
install:
  - install
   # - ./run.sh install_ppa




before_script:
  - before_script

script:
  - script
  
after_script:
  - after_script

after_success:
  - after_success


after_failure:
  - after_failure
 # - ./run.sh push_to_github

#http://www.jedi.be/blog/2010/08/30/capturing-the-screen-of-your-virtual-machines-using-x-vnc-rdp-or-native/

