language: bash 
#language: python
env:
  fast_finish: true
  global:
   - secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="
  matrix:
  - fast_finish: true
 # - ONE=one

#build:
#  - true
   
before_install:
#  - sudo apt-get install tree
  - chmod u+x ./run.sh 
  - chmod u+x ./SCRIPTS/*.sh
  - ./run.sh library 
  
install:
  - ./run.sh install_deps > /dev/null
  
before_script:
  - ./run.sh tests &


script:
  - ./run.sh record_start
  
after_script:
  - ./run.sh push_to_github
  
after_success:
  - ./run.sh record_finish
  
after_failure:
  - echo after_failure

