language: bash 
cache: apt

env:
  fast_finish: true
  global:
    - secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="
    - TIMEOUT=1000

# whitelist
branches:
  only:
    - develop
    
before_install:
  - mkdir /tmp/log
  - chmod u+x ./run.sh 
  - chmod u+x ./SCRIPTS/*.sh
  - ./run.sh library
  
install:
  - ./run.sh install_deps
  
before_script:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - dbus-launch pulseaudio --start
  - export WIDTH=1024
  - export HEIGHT=768
  - export SCREEN="0 ${WIDTH}x${HEIGHT}x16"

script:
  - ./run.sh debug_screen
  - ./run.sh tests &
  - ./run.sh record_start 
  
after_script:
  - echo after script

after_success:
  - ./run.sh push_to_github


after_failure:
  - echo failure


