language: bash 
#language: python


env:
  global:
   - secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="
  matrix:
   - ONE=one







before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq recordmydesktop x11-apps libpulse-dev pulseaudio dbus-x11 espeak mbrola-us2 pulseaudio-utils
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - dbus-launch pulseaudio --start
build:
  - true
script:
  - "recordmydesktop --no-cursor  --output=session.ogv &"
  - paplay <(espeak -vmb-us2  "Ok, let's get rickrolled" --stdout)
  - "firefox www.youtube.com/watch?v=oHg5SJYRHA0 &"
  - sleep 10
  - paplay <(espeak -vmb-us2  "That bored me" --stdout)
  - killall firefox
  - sleep 2
  - paplay <(espeak -vmb-us2  "Much better now" --stdout)
  - sleep 2
  - paplay <(espeak -vmb-us2  "I have to go. See you next build!" --stdout)
  - killall recordmydesktop
  - while pgrep -x recordmydesktop > /dev/null ; do sleep 1; done # wait for transcoding
  - tar cf artifacts.tar session.ogv
  - ls -l session.ogv
  - mv session.ogv /tmp
  
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - ./script.sh
