language: bash 
#language: python
env:
  global:
   - secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="
  matrix:
   - ONE=one
before_install:
  - chmod u+x ./run.sh 
  - chmod u+x ./SCRIPTS/*.sh
  - ./run.sh before_install
after_install:
  - ./run.sh after_install
before_script:
#  - ./SCRIPTS/youtube.sh
  - ./run.sh before_script
build:
  - true
script:
  - echo ./run.sh script
after_script:
  - ./run.sh after_script
