#http://superuser.com/questions/540391/x-error-of-failed-request-badcursor-invalid-cursor-parameter-when-recording-x  


language: python 
cache: apt

env:
  global:
    secure: "XyxrwdEK1RxYFDzmU1+WCkEL0MlDlPdF9wP6kDjDoOAs6o5+oRUqVXP8uCdahREJZaL3n4PpnSa1X7UcbC+E6q/IY7BYdNCCQ0v2xYOMf7H5op7WF4x0Sb2DhzcJGx9E5R1xJZHb7y5t/AAB61k97UQxwtA3LEI6LS2FdSPrghY="


  #  secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="



matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - develop
    
before_install:
  - echo before install


  

  
install:
  - echo let us start
  - chmod u+x *.sh . -R
  - mkdir /tmp/log
  - mkdir /tmp/PRODUCT
  - ./travis.sh
  


before_script:
  - echo before_script

script:
  - echo script1
  
after_script:
  - echo after_script

after_success:
  - echo after_success


after_failure:
  - echo after_failure
 # - ./run.sh push_to_github

#http://www.jedi.be/blog/2010/08/30/capturing-the-screen-of-your-virtual-machines-using-x-vnc-rdp-or-native/

