#http://superuser.com/questions/540391/x-error-of-failed-request-badcursor-invalid-cursor-parameter-when-recording-x  


language: ruby 
cache: apt

env:
  global:
    - secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="
    - TIMEOUT=1000
    - WIDTH=1024
    - HEIGHT=768
    - COLORS=16
    - timeout_record=60
    - timeout_task=7
    - dir_log=/tmp/log
    - mute_err=false
    - mute_out=true
